version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - python3 --version

  build:
    commands:
      - echo "Build step (nothing to compile)"
  
  post_build:
    commands:
      - chmod +x scripts/*.sh

artifacts:
  files:
    - '**/*'
  name: simple-web-project
